### ISSUE TITLE
test_convert.sh: line 4: realpath: command not found

### ISSUE THREAD

**Issue by jalibu** [sdetweil/MMM-Config#10]
**System**
MacOS

**Steps to reproduce**

1. Clone MMM-Config
2. _npm i_ inside MMM-Config folder (successful without problems)
3. Start MM with "npm run server"
4. Check Server Logfiles

```
[ERROR] stderr 2: /Users/me/git/MagicMirror/modules/MMM-Config/test_convert.sh: line 4: realpath: command not found
stat: illegal option -- -
usage: stat [-FlLnqrsx] [-f format] [-t timefmt] [file ...]
stat: illegal option -- -
usage: stat [-FlLnqrsx] [-f format] [-t timefmt] [file ...]
find: ../default: No such file or directory
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module '/Users/me/git/MagicMirror/scripts/buildschema3.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

**Comment by jalibu** [comment]
Unfortunately there is no realpath on MacOS :-/

You could consider using an own realpath function that calls the native function (if present) or 
```
realpath() {
    path=`eval echo "$1"`
    folder=$(dirname "$path")
    echo $(cd "$folder"; pwd)/$(basename "$path"); 
}
```
Source: https://stackoverflow.com/questions/3572030/bash-script-absolute-path-with-os-x

**Comment by jalibu** [comment]
Or just add this to your readme:
```
MacOs Users must
install [homebrew](https://brew.sh/)
brew install coreutils
```

**Comment by sdetweil** [comment]
or add that to the postinstall script

**Comment by sdetweil** [comment]
realpath isn't in the coreutils anyhow..

I have pushed a fix  give it a try, looks good here, 
git pull

**Comment by sdetweil** [comment]
I believe that this is fixed for you, as you also tested the port fix successfully

please config

**Comment by jalibu** [comment]
I uninstalled coreutils (which solved the problem for me yesterday) and it still works. good job

**Comment by sdetweil** [comment]
thanks for the fast update
