### ISSUE TITLE
Feature Request: Set of possible values

### ISSUE THREAD

**Issue by jalibu** [sdetweil/MMM-Config#11]
Very nice module!

When I checked compatibility with my modules, I thought it would be great to know which values are allowed to use/supported for some config fields. For some fields also the description would be nice.
Examples:
**currencyStyle** allows one of ['symbol', 'name', 'code'] where default is 'code'
**scroll** allows one of ['vertical', 'horizontal', 'none'] where default is 'vertical'
![image](https://user-images.githubusercontent.com/25933231/119389896-896e7580-bccc-11eb-9624-430f9c121191.png)

I first thought one could provide this information as parsable comment next to each config entry but unfortunately that does not work for minified modules.

Perhaps an optional mmm-config.json would do it?

That's just an idea :-)

**Comment by sdetweil** [comment]
yes, it would be nice if the data was available for those cases where there are specific choices. but it is not.

for the smart-mirror project, plugin authors are required to provide the form info, including all choices,  and choice styles one,  some, ...

I cannot require it here

IF there was an additional file, I would require the same info, and the layout would be perfect. 

there are a lot of old modules still in use, for which no author would create such a file

**Comment by sdetweil** [comment]
actually, that gives me another tool idea. I could SAVE the structure I need as I am building it (over and over).. and those that care could adjust it, so I could use it instead of the construction..   

hmmm..  more fun

**Comment by sdetweil** [comment]
well, saving the structure didn't take much at all.. 5 lines of code.. 

gotta fix a couple read back in bugs..

**Comment by sdetweil** [comment]
so, I just pushed first multi-module support, which includes an option to generate the form input file for each module as it goes by.

later I will USE those files  (if present) instead of constructing them..

to get the files, go to the modules folder 
and execute 

node scripts/buildschema4.js ../defaults.js saveform >schema3,json

for each module located in the modules folder a file called schema.json will be generated 

the file has three sections

1. the data layout (constructed from the defaults section)
2. for FORM layout (how u want the form to appear), generated
3. a value section, which is what the 'default' would be for a new instance

for enums and other selction type items, they would be described in the 1st section
see https://github.com/jsonform/jsonform/wiki

for the technical doc on the form structure, its all json.  

they have a site where u can input/paste your stuff to see how it might operate
https://jsonform.github.io/jsonform/playground/index.html
each module schema.json should paste into the playground without modifications

**Comment by sdetweil** [comment]
expounding on the prior post

its simple to make thing s a choice (enumerated) list

my MyCovid19 module has 4 chart modes
but the field is a string 
```
            "chart_type": {
              "type": "string"
            },
```
if I change it to add the choices,  it looks like this
```
            "chart_type": {
              "type": "string"
              "enum": [
                  "cases",
                  "cumulative_case",
                  "deaths",
                  "cumulative_deaths"
               ]                      
            },
```

when the form is presented, it is now a dropdown list, with only those choices
u can set a default too , if the 1st isn't the one
```
                  "default":"cumulative_cases"
```

**Comment by sdetweil** [comment]
just pushed the latest

added a new script, 
```
create_schema.sh
```
which will generate the schema.json files for all modules installed (not over-writing any already present)

and will now USE the schema file if present, so any customizations will be used.  

its impossible to guess (correctly!) what should be inside [] or {}

**Comment by sdetweil** [comment]
pushed 1st version  for full testing,
in the multi-module branch

````
git pull
git fetch original 
git checkout multi-module
npm install
```

**Comment by BKeyport** [comment]
I don't have the create_schema.sh in the multi-module fork. Please advise.

**Comment by sdetweil** [comment]
sorry, create_forms.sh
(an ls would have shown you)

**Comment by BKeyport** [comment]
Yeah,  well, I saw that was present, I just didn't want to run it without knowing what it does. :)

**Comment by BKeyport** [comment]
pi@testbox:~/MagicMirror/modules/MMM-Config $ ./create_forms.sh 
internal/modules/cjs/loader.js:888
  throw err;
  ^

Error: Cannot find module '../defaults.js'
Require stack:
- /home/pi/MagicMirror/modules/MMM-Config/scripts/buildschema4.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Config/scripts/buildschema4.js:2:17)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/pi/MagicMirror/modules/MMM-Config/scripts/buildschema4.js' ]
}

**Comment by sdetweil** [comment]
do 
```
./test_convert.sh override
```
they use the same pgm, with different parms

I ran it here without problem

**Comment by BKeyport** [comment]
The method mentioned in https://github.com/sdetweil/MMM-Config/issues/11#issuecomment-848411385  works for making dropdowns. I use it in MMM-Worldclock.

**Comment by sdetweil** [comment]
promoted as only version,   need to write a new issue with instructions, leave open for now

**Comment by sdetweil** [comment]
promoted to production

**Comment by jalibu** [comment]
I added a schema.json file for MMM-Jast and it seems to work

**Comment by sdetweil** [comment]
thanks... can we close this now?
