### ISSUE TITLE
Not Saving

### ISSUE THREAD

**Issue by BKeyport** [sdetweil/MMM-Config#13]
Here's the config files... 
[config.js.2021-05-27T01.46.58.txt](https://github.com/sdetweil/MMM-Config/files/6551003/config.js.2021-05-27T01.46.58.txt)
[config.js.2021-05-27T03.22.07.txt](https://github.com/sdetweil/MMM-Config/files/6551004/config.js.2021-05-27T03.22.07.txt)
[config.js.2021-05-27T03.26.29.txt](https://github.com/sdetweil/MMM-Config/files/6551005/config.js.2021-05-27T03.26.29.txt)
[config.js.2021-05-27T03.27.13.txt](https://github.com/sdetweil/MMM-Config/files/6551006/config.js.2021-05-27T03.27.13.txt)
[config.js.2021-05-27T03.27.31.txt](https://github.com/sdetweil/MMM-Config/files/6551007/config.js.2021-05-27T03.27.31.txt)
[config.js.2021-05-27T03.28.47.txt](https://github.com/sdetweil/MMM-Config/files/6551008/config.js.2021-05-27T03.28.47.txt)
[config.js.2021-05-27T03.29.38.txt](https://github.com/sdetweil/MMM-Config/files/6551009/config.js.2021-05-27T03.29.38.txt)
[config.js.txt](https://github.com/sdetweil/MMM-Config/files/6551010/config.js.txt)

**Comment by BKeyport** [comment]
.txt added to filenames to get them on system.

**Comment by BKeyport** [comment]
[defaults.js.txt](https://github.com/sdetweil/MMM-Config/files/6551026/defaults.js.txt)

**Comment by BKeyport** [comment]
There's everything requested. Don't know how to attach to the forum, so it's here.

**Comment by sdetweil** [comment]
is that all of them in the sequence? 
01:46 no Multi-month
03:22 Multi-month,    but no position set, so not visible (position set to none)
03:27 moved calendar to top_bar, from top left, position on calendar removed (set to none)
03:28 Multi-month, moved to top_bar, calendar set to top_left
03:29 Multi-month, position removed, calendar position still set to none

looks like it is writing fine, and positions are working..  the disable flag worked to get multi-moth written out..

I can't tell i u set disabled on any other module...  disabled is a checkbox in each module section
position is at the bottom...

**Comment by BKeyport** [comment]
3:22 - Added MM - attempted to set position to top_bar, checked disabled box on all default modules except clock. 
3:27 - Well, that didn't work, try setting position to none on calendar to make it disappear. 
3:28 - OK, that worked, move multi-month only to top_bar. - multi-month disappeared. 
3:29 - Multi-month attempt to flip to horizontal display (monthsVertical: false) 

Current state - defaults are active, multi-month is vertical (monthsVertical: true)

**Comment by sdetweil** [comment]
i saw the change tp vertical:false, but position none

if it HAS NONE in config.js, that is what it will be..  
add debug:true to the config

start 
npm start >somefile 2>&1
do you test (with changing disabled too)
and then send me somefile

I haven't changed the helper except for the socket addition..  so the form saving logic hasn;t changed

**Comment by BKeyport** [comment]
Not quite following what you're saying here, Sam.

**Comment by sdetweil** [comment]
add debug:false to the MMM-Config entry in config.js

start MM saving its console output

use the form to make changes, including disabling modules (default modules too)

and then hit submit

the debug reports on the  saving process..

**Comment by BKeyport** [comment]
[somefile.txt](https://github.com/sdetweil/MMM-Config/files/6556042/somefile.txt)

In this config I made a change to Multi-Month (convert to horizontal mode), and tried to disable complements (failed)

**Comment by sdetweil** [comment]
cool info, thanks.. found it.. the merge tool I am using has a quirk, if the value (key) is not in the source, it doesn't copy the key from the new data either..  doah... 

so, where disabled was NOT in config.js, it did NOT copy the new setting...

git pull and try it out..

**Comment by BKeyport** [comment]
Indeed, that fixed it... Now off to see what else I can break. 🤣

**Comment by sdetweil** [comment]
cool. I'm gonna close this one..
