### ISSUE TITLE
MMM-Flipclock causes failure. 

### ISSUE THREAD

**Issue by BKeyport** [sdetweil/MMM-Config#14]
[config.js.txt](https://github.com/sdetweil/MMM-Config/files/6556526/config.js.txt)

Here's the config file -The colon (:) is causing the problem. When the separator is set to "-" it works. 

Oddly, config:check reports correct file, but then throws an error on line 55 (which is the calendar module) 

If you look, the config for flipclock is totally messed up.

**Comment by sdetweil** [comment]
great job.. I JUST put the code in that is causing fliplock...lol

**Comment by sdetweil** [comment]
😜

**Comment by BKeyport** [comment]
heh.

**Comment by sdetweil** [comment]
fix uploaded, git pull

**Comment by BKeyport** [comment]
Had to restart MM a couple of times, but it appears to have fixed it once I copied in and old backup and changed the string back to :

**Comment by sdetweil** [comment]
cool
