### ISSUE TITLE
Don't work with MMM-CalendarExt2 (last one, I promise!) 

### ISSUE THREAD

**Issue by BKeyport** [sdetweil/MMM-Config#15]
While the project is dead, I still use it, as I'm sure many do. You might not want to tackle this one. 

On fresh installs, you can't create the calendar settings at all, just gives us one field. Once you put a config into the file via text editor, it'll fill those dialogs with "object" tags. Here's my sanitized config if you wanna take a look. the URLs in file is to calendars that I don't care if they're public or not. 

[config.js.sanitized.txt](https://github.com/sdetweil/MMM-Config/files/6557232/config.js.sanitized.txt)

**Comment by sdetweil** [comment]
you should end up with a big text editor field, to put the whole blob in. 
I spent a LOT of time working on that

**Comment by sdetweil** [comment]
pushed fix for this
