### ISSUE TITLE
various modules missing config params

### ISSUE THREAD

**Issue by sdetweil** [sdetweil/MMM-Config#17]
author didn't include them in defaults.. 

can correct with schema file..   not sure otherwise

MMM-Bustimes coded 
```
destinations: null
```
instead of 
```
destinations: []
```
when usage  is like this
```
destinations: ["9341","9562"]
```

- MMM-WeeklySchedule
- MMM-WiFiPassword (QR code doesent render anymore after installing your module)
-     qrcode library collision in issue #16 
- Standard Weather (missing location variable and openweathermap api)

**Comment by sdetweil** [comment]
i propose that the module packages some customized schema files (particularly for the no longer maintained modules)
i can take PRs from anyone to add/correct the schema file

the module will check for one provided by each module and use THAT if found
then check if we have one, use that 
otherwise generate

**Comment by BKeyport** [comment]
Seems this is a tie-in to #11 and #20 and others - might as well tag them together.

**Comment by sdetweil** [comment]
well, this is  ' your module doesn't list my module parameters"..
and I look, and sure enough, the author didn't include them in the code..
so I can 'fix' this, but have to ship a schema file  for that module,  unless the author chooses to
so its really a different problem.. 
it USES the function in #11 to save the schema and edit it. but provides a different shipping solution

**Comment by sdetweil** [comment]
see the latest README for all the ways to improve the config presentation for a module.
