### ISSUE TITLE
MMM-Worldclock missing configuration pieces

### ISSUE THREAD

**Issue by BKeyport** [sdetweil/MMM-Config#19]
I'm missing two clock config items for MMM-Worldclock, both within the clock array. 

the full set is: 
title: "some descriptive text" 
timezone: "Timezone" 
flag: "Two letter code" (ISO 3166-1-alpha-2 code)
altflag: "somefile.png" - flag for non-country flags (IE: globe for GMT). 
timeFormat: "moment.js string" - Override time format from above. 

If you tell me how you achieve the list of options, I can adjust my module to match. I've got an idea on how to make this better per module, but I'm trying to come up with a method before making suggestion.

**Comment by sdetweil** [comment]
see issue #11

**Comment by sdetweil** [comment]
in your code, you  don't list the other fields
```
 clocks: [      {
        title: "Seoul",        
        timezone:"Asia/Seoul",        
        flag:"kr",      
},    ]
 ```

so, add them,  run the create_schema.sh

edit the schema.json in your module foilder and add 
   in the schema section for the variables 
```
   "enum": [
    "option1",
    "option2",
     ....
   ]
```

**Comment by BKeyport** [comment]
Oh, so you're scraping the code for your module? Cool. I'll update the defaults then - was planning to do that anyway to show off the new functionality.

**Comment by sdetweil** [comment]
I don't understand what u just said?  I am not scraping anything.. 
if u want to customize the form, u can, I generated it.. 
then I will USE the customized form, if present.. I don't have to guess..

**Comment by BKeyport** [comment]
Initially to create the form, you look at the defaults, is what I mean. I've updated my module to have a modern set of defaults now, in any case.

**Comment by sdetweil** [comment]
correct, I look at the defaults. thats all there is

see the customizef form for MMM-CalendarExt2 in the schemas folder..  many authors no longer exist or don't update
so, someone customizes and I will ship the file..    what choice is there...

**Comment by BKeyport** [comment]
OK, I've got the schema.json in the directory, and it appears to be creating the scheme correctly in MMM-Config now from scratch and with an existing. 

If I update my module with the schema.json file in the git package, it'll make it compatible for every install of MMM-Config, correct?

**Comment by sdetweil** [comment]
yes, if they use mmm-config it will use your schema file.

did u add the dropdown choices

**Comment by BKeyport** [comment]
I did not. Not sure how to do so.

**Comment by sdetweil** [comment]
see issue #11

**Comment by BKeyport** [comment]
added: 
```
    "style": {
              "type": "string"
              "enum": [
                "top",
                "bottom",
                "left",
                "right"
                ],
            },
```

Result - 
![image](https://user-images.githubusercontent.com/44744076/120951486-c8a1bb00-c6fd-11eb-9454-c91490e97482.png)

It will eventually give up and state magicmirror isn't running, which it is.

**Comment by sdetweil** [comment]
it's json, need a comma after "string", and not after ]

**Comment by BKeyport** [comment]
Got it. Works now.

**Comment by sdetweil** [comment]
also, one thing u can do to make the choices descriptive , is to add a titlemap to the form side of the variable
i'm using this for the restart option in config now
```
        {
          "title": "restart",
          "key": "MMM-Config.config.restart",
          "titleMap": {
            "none": "no restart after save",
            "pm2": "use pm2 to restart, will autodetect which pm2 instance to restart",
            "static": "MagicMirror started with npm start, may cause flaky windows",
            "docker":" not yet implemented, same as none"
          }
      },
```

**Comment by sdetweil** [comment]
also, can add descriptive text under an option in form section with 
"description":"whatever text u want"
(remember trailing comma on line before if u add a new line)

**Comment by BKeyport** [comment]
Descriptions added, Neat!

**Comment by sdetweil** [comment]
yes, it starts to look like you cared!!... 

just for info, the form library is here 
https://github.com/jsonform/jsonform
