### ISSUE TITLE
Suggestion: allow for config.csv that would list the field names and instructions for module. 

### ISSUE THREAD

**Issue by BKeyport** [sdetweil/MMM-Config#20]
I was thinking, to ease people's use of the config tool, how about letting authors specify instructions and field lists? 

In my example here (For MMM-Worldclock), it would give you the field name, and instructions on how to config it. I used the pipe "|" to indicate that a field is part of an array inside another field. This example I whipped up into a CSV, but clearly you could specify as needed for your use. 

You look for say, "config.csv" in the module's root directory, and if present, it would be parsed to give user guidance right on the configuration page. 

This might be able to be done with the readme.md file, but a dedicated file option for authors willing to do it would be best, IMO. 

```
Field,Instruction
timeFormat,Overall Time Format. See http://moment.js for examples. 
style ,"How to display the clocks in relation to their flags and titles. Possible values: ""top"", ""bottom"", ""left"", ""right"""
offsetTimezone,Show a difference between the timezone shown here and the timezone specified in the clock below. Values are here: https://github.com/moment/moment-timezone/blob/develop/data/packed/latest.json
clocks | title,"A string to define the clock's title. If blank, will be the timezone. "
clocks | timezone,Timezone of the clock. Values are the same list as the offsetTimezone values. 
clocks | flag,"You can specify a flag, use a value from the ""Alpha-2 Code"" list here: https://www.iso.org/obp/ui/ - search/code/"
clocks | altflag,"There is the ability to display an alternate flag of your choice. Image file must be in the MMM-Worldclock directory. Specify it's name here. Must be square, must be centered. "
clocks | timeFormat,This clock's Time Format. See http://moment.js for examples. 
```

**Comment by sdetweil** [comment]
see #11
