### ISSUE TITLE
Suggestion - Restart? 

### ISSUE THREAD

**Issue by BKeyport** [sdetweil/MMM-Config#21]
Would it be possible to optionally restart upon saving config? I'm assuming the hard part would be determining how user started MM - PM2/Docker/or raw. 

Two buttons, [save and restart] [save only] 

Just a thought.

**Comment by sdetweil** [comment]
set the existing restart config option

**Comment by sdetweil** [comment]
I don't know how to restart  docker instance, but could do it.

**Comment by BKeyport** [comment]
I'm not finding a restart option anywhere, this is why I suggested.

**Comment by sdetweil** [comment]
in my module options
showQR
forceupdate
restart
debug

and in my doc

**Comment by BKeyport** [comment]
Ahh, I see it. I was looking for a checkbox, and it's a text field.

**Comment by BKeyport** [comment]
Not clear, do I need 
"PM2:mm" 
or just "mm"?

**Comment by sdetweil** [comment]
pm2:mm

**Comment by BKeyport** [comment]
OK, Thanks.

**Comment by sdetweil** [comment]
I had thought about auto detecting the pm2 instance.  then it could be a dropdown

**Comment by BKeyport** [comment]
Actually, I think that would be best reconfigured - maybe set it up to be "command to restart MM" 

So, the Pm2 user would be "pm2 restart MagicMirror" (by your script), or "pm2 restart mm" on my system.

**Comment by sdetweil** [comment]
but I can figure it out. pm2 info will give me the paths, and I know which one we are running on. I don't need the name.  I can use the number

**Comment by BKeyport** [comment]
Okay. I'll shaddup and let you work. :)  

Back to work on my test box..

**Comment by sdetweil** [comment]
pushed update to address this

**Comment by BKeyport** [comment]
Works.
