### ISSUE TITLE
Not a big surprise, but....

### ISSUE THREAD

**Issue by BKeyport** [sdetweil/MMM-Config#23]
module does not work with symbolic link style config.js 

on my production box, I have config.js and custom.css both symbolic link to my own directory for ease of access, and ease of backup. When saving a config, it'll override the symbolic link with it's own config.js - and not put it in my directory. 

Not a big surprise, but you might want to make a note in the readme or fix it. Your choice. 😉

**Comment by sdetweil** [comment]
well, it doesn't overwrite it, it renames the old file, which should have renamed the the file on the other end
thanks will look at that..

**Comment by sdetweil** [comment]
try latest push,

does copy old to save
overwrite old, which should write thru the symlink

**Comment by BKeyport** [comment]
Works. 

Restart failed for some reason, now. 

my PM2 instance is "mm"

**Comment by sdetweil** [comment]
remember now I discover the pm2 instance. I do not use the name .. only the number

**Comment by sdetweil** [comment]
is the link still good?

**Comment by BKeyport** [comment]
Symlink still shows as symlink, and changes are made to test.js (where the symlink points)

**Comment by sdetweil** [comment]
and if you use npm start to test MM, vs pm2..  does it work ok?

**Comment by BKeyport** [comment]
As for the PM2 problem  - here's my process. - didn't restart on save, but manual restart works perfectly. Restarted and added the extra month on multimonth (What I changed to check) 


 Describing process with id 0 - name mm 
┌───────────────────┬───────────────────────────────────┐
│ status            │ online                            │
│ name              │ mm                                │
│ namespace         │ default                           │
│ version           │ 2.15.0                            │
│ restarts          │ 2                                 │
│ uptime            │ 107s                              │
│ script path       │ /home/pi/MagicMirror/run-start.sh │
│ script args       │ N/A                               │
│ error log path    │ /home/pi/.pm2/logs/mm-error.log   │
│ out log path      │ /home/pi/.pm2/logs/mm-out.log     │
│ pid path          │ /home/pi/.pm2/pids/mm-0.pid       │
│ interpreter       │ bash                              │
│ interpreter args  │ N/A                               │
│ script id         │ 0                                 │
│ exec cwd          │ /home/pi/MagicMirror              │
│ exec mode         │ fork_mode                         │
│ node.js version   │ N/A                               │
│ node env          │ N/A                               │
│ watch & reload    │ ✘                                 │
│ unstable restarts │ 0                                 │
│ created at        │ 2021-06-15T20:26:15.753Z          │
└───────────────────┴───────────────────────────────────┘
 Revision control metadata 
┌──────────────────┬────────────────────────────────────────────────┐
│ revision control │ git                                            │
│ remote url       │ https://github.com/MichMich/MagicMirror.git    │
│ repository root  │ /home/pi/MagicMirror                           │
│ last update      │ 2021-06-15T20:26:16.101Z                       │
│ revision         │ 491f5aa7769a12de7f20f201de0078704c158a8d       │
│ comment          │ Merge pull request #2510 from MichMich/develop │
│                  │                                                │
│                  │ Release v2.1                                   │
│ branch           │ master                                         │
└──────────────────┴────────────────────────────────────────────────┘
 Divergent env variables from local env 
┌────────────────┬─────────────────────────────────────┐
│ PWD            │ /home/pi/MagicMirror                │
│ SSH_CONNECTION │ 192.168.1.145 1036 192.168.1.204 22 │
│ XDG_SESSION_ID │ 6                                   │
│ SSH_CLIENT     │ 192.168.1.145 1036 22               │
│ OLDPWD         │ /home/pi                            │
└────────────────┴─────────────────────────────────────┘

**Comment by sdetweil** [comment]
what does pm2 logs  show 
(they are in the ~/.pm2/logs folder )

**Comment by BKeyport** [comment]
must have just been a transient problem. Worked when I tried it again just now to capture fresh data.

**Comment by sdetweil** [comment]
i hate when that happens!..

**Comment by BKeyport** [comment]
So, yes, everything works again. Back to work for me.

**Comment by sdetweil** [comment]
lol..
