### ISSUE TITLE
Opening web module link

### ISSUE THREAD

**Issue by ikze** [sdetweil/MMM-Config#26]
Hi! 

Thank you for your work, it's such an easy task to follow you guides as a beginner.
I would like a little bit of help if I may, as I can't load the web modules and creating modules the old way is not as handy
![config html](https://user-images.githubusercontent.com/36470733/139161212-54609021-f930-4025-9b65-a43ea31068f8.jpg)
![review](https://user-images.githubusercontent.com/36470733/139161218-20427343-5a1e-4044-ad83-8a95ac2552f6.jpg)

.

**Comment by sdetweil** [comment]
i'm gonna close this , if its still a problem, re-open
