### ISSUE TITLE
No info displayed on the config.html page

### ISSUE THREAD

**Issue by ianperrin** [sdetweil/MMM-Config#32]
Hi @sdetweil 

Love the idea and concept - great work.

I was attempting to start testing compatibility with my modules, but I'm having issues displaying the config page.

If I browse to http://ip:port/modules/MMM-Config/review, the browser is redirected to http://magicmirror:8080/modules/MMM-Config/config.html?port=8303 and a "Page Not Found" (404) error is displayed

If I browse to http://ip:port/modules/MMM-Config/config.html or http://ip:port/modules/MMM-Config/config.html?port=8303, no information other than header text is displayed.

I'm running MM 2.17.1 in a docker container.

The log file contains the following error:
````
[14.11.2021 12:31.13.948] [ERROR] stderr 2: node:internal/fs/utils:344
    throw err;
    ^

Error: ENOENT: no such file or directory, scandir '/opt/magic_mirror/modules/MagicMirror/translations/'
    at Object.readdirSync (node:fs:1390:3)
    at Object.<anonymous> (/opt/magic_mirror/modules/MMM-Config/scripts/buildschema4.js:174:4)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {

  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '/opt/magic_mirror/modules/MagicMirror/translations/'
}
````

The browser console displays the following errors
````
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (bootstrap.css.map, line 0)    http://<<ip>>:<<port>>/modules/MMM-Config/node_modules/jsonform/deps/opt/bootstrap.css.map
[Error] Failed to load resource: The network connection was lost. (socket.io, line 0)   http://<<ip>>:8303/socket.io/?EIO=4&transport=polling&t=NqUSD0A
[Error] Failed to load resource: The network connection was lost. (socket.io, line 0)   http://<<ip>>:8303/socket.io/?EIO=4&transport=polling&t=NqUSDBW
````

Any ideas what I've missed?

Thanks

**Comment by sdetweil** [comment]
you do not open the html directly
the instructions say , if not using the qrcode

```
Otherwise, use a browser to open http://machine_name:MM_Port/modules/MMM-Config/review
```

**Comment by sdetweil** [comment]
also, looks like u have some misconfiguration under docker

opt/magic_mirror/modules/MagicMirror/translations

**Comment by ianperrin** [comment]
Hi @sdetweil 

Thanks for the reply.

I was originally using the  http://machine_name:MM_Port/modules/MMM-Config/review url but it was failing to redirect. As a result I tried the direct url to the config.html file.

Then, when I set the `qrcode` option to true, the qrcode image did not display.

I think I've found the issue - the redirect and qrcode imageurl require the machine name to be resolvable. Which it my case it is not. As a result, the redirect fails and the qrcode is not displayed.

I've submitted a pull request (#33 ) which resolves this issue

Unfortunately, this hasn't solved the issue of the config page being blank. If you have any further ideas that would be great

**Comment by sdetweil** [comment]
my web config page is trying to open a socket back to the MM running in the container..  but the web page is running on the host..

so port 8300 (where my module is expecting connection from the html page to transfer the form and data)  (or whatever) needs to be mapped into the docker container too ..

**Comment by sdetweil** [comment]
ok, I changed the module to remove the hard coded url.. try it again (git pull ) 
I didn't use your pr, but appreciate it  (I had two branches to fix)

**Comment by ianperrin** [comment]
Thanks

So I've added port 8300 to the configuration for the docker container, as follows
````
    ports:
      - 8080:8080/tcp
      - 8300:8300/tcp
````

The log file then reads

````
__snip__
[14.11.2021 16:35.29.222] [LOG]   MMM-Config received a socket notification: CONFIG - Payload: [object Object]
[14.11.2021 16:35.29.223] [LOG]   command =/opt/magic_mirror/modules/MMM-Config/test_convert.sh override
[14.11.2021 16:35.29.224] [LOG]   Starting module helper:MMM-Config
[14.11.2021 16:35.29.224] [LOG]   execing /opt/magic_mirror/modules/MMM-Config/test_convert.sh override
[14.11.2021 16:35.29.416] [LOG]    got port=8300
__snip__
[14.11.2021 16:35.29.574] [LOG]   QRCode build done
[14.11.2021 16:35.31.672] [LOG]   stdout: completed
````

It then includes the same error:
````
[14.11.2021 16:35.31.674] [ERROR] stderr 2: node:internal/fs/utils:344
    throw err;
    ^

Error: ENOENT: no such file or directory, scandir '/opt/magic_mirror/modules/MagicMirror/translations/'
    at Object.readdirSync (node:fs:1390:3)
    at Object.<anonymous> (/opt/magic_mirror/modules/MMM-Config/scripts/buildschema4.js:174:4)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {

  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '/opt/magic_mirror/modules/MagicMirror/translations/'
}
````

The logs are then repeated this time with port 8301
````
[14.11.2021 16:35.29.416] [LOG]    got port=8301
````

FYI, I noticed a similar issue (#5) contained a similar error (`no such file or directory, scandir '/opt/magic_mirror/modules/MagicMirror/translations/'`) - but not sure if my issue is related...?

**Comment by ianperrin** [comment]
> ok, I changed the module to remove the hard coded url.. try it again (git pull )
> I didn't use your pr, but appreciate it (I had two branches to fix)

Thanks - the qrcode now appears and the redirect displays the config.html page

Per my comment above, adding the port to the docker config hasn't resolved the "no such file or directory" issue with the translations so it would be good if we can find a fix for that too

Also, now the qrcode is displaying, I noticed the embedded link still uses the machine name - https://github.com/sdetweil/MMM-Config/blob/281e9d8a94a88c54ef046d120b94f7f6de6776a6/node_helper.js#L152

Might be worth fixing this if you get the chance ;)

**Comment by sdetweil** [comment]
yes, translations was my fault  a fix from issue 5 was lost ..

use the new branch 

if I change that qr doesn't work locally

**Comment by sdetweil** [comment]
![Screenshot_20211114-111827_Camera](https://user-images.githubusercontent.com/1498142/141691369-adc3ad89-a26a-412f-b3b7-792aa2b9c1ac.jpg)

**Comment by ianperrin** [comment]
> yes, translations was my fault a fix from issue 5 was lost ..
> 
> use the branch 'new'

No worries - I've switched the new branch and moved a step further. 

Now when displaying the config page (via the redirect) I get the following error in the console
````
SyntaxError: JSON Parse error: Unexpected identifier "modules".     form-client.js:39 
````

**Comment by sdetweil** [comment]
ok, can u post the output of
in my module folder 
defaults.js
and schema3.json 

if there are any apikeys, etc, u may want to email them to me rather than attach here.. 

you could run the constructor manually, have to be IN the container, in my module folder do 

node scripts/buildschema4.js ./defaults.js >schema3.json

**Comment by sdetweil** [comment]
is this resolved?

**Comment by ianperrin** [comment]
Thanks for checking in @sdetweil I got the module to display using the new branch, so at some point will revisit support for my modules 😉

**Comment by sdetweil** [comment]
oh, I added support for the schema generator to save for just one module 

create_forms.sh  [ modulename ] 

if no modulename is specified schema will be saved in each modules folder

schema.json

this gives up a good starting place..
