### ISSUE TITLE
No modules displayed, Only mmm-Config header text

### ISSUE THREAD

**Issue by ecirpnaes** [sdetweil/MMM-Config#38]
As per title, if I load the module into the config.js, using the defaults specified in the docs, when I navigate to the ../modules/MMM-Config/config.html, all I see is the "Configure MagicMirror and modules" header line on the page and nothing else. Just a blank html page.

Is there a trick to getting it to display my other modules? My mirror functions normally...

Doing a "View Source" on the config.html page shows that it is loading all the .js libraries.

**Comment by sdetweil** [comment]
not supposed to go to config.html

supposed to go to review

unless u use the qr code

**Comment by sdetweil** [comment]
i've updated the images to blank out the URL at the time I took the screen shots..

**Comment by ecirpnaes** [comment]
Much obliged. I looked all over for the proper page to navigate to and yet somehow I still missed the bold text in the instructions.

**Comment by sdetweil** [comment]
wasn't bold til after u reported the problem..my fault.  

I fixed the images to remove the mold url, and bolded the correct url.  thanks for the push
