### ISSUE TITLE
what to do about using JS in the config.js to create module config info

### ISSUE THREAD

**Issue by sdetweil** [sdetweil/MMM-Config#49]
in the MMM-HomeAssistantDisplay module if you want to create multiple entries for switches/sensors rather than coding each they show using js 
```js
// entity list info
let perimeterWindows = [
    {
        entity: "cover.athom_garage_door",
        name: "Garage Door"
    },
    {
        entity: "light.switchlinc_dimmer_48_b8_33",
        name: "Hall light"
    },
    {
      entity: "binary_sensor.athom_garage_door_status",
      name:"fooo"
    }

];
// variable for later use
let perimeterWindowSections = [];

// code to convert variable list to array of items used in module config
perimeterWindows.forEach((item, i) => {
    perimeterWindowSections.push({
        triggerEntities: [
            item.entity
        ],
        displayTemplate: `
        {% if states.${item.entity}.state == "on" %}<i class='mdi mdi-window-open'></i> ${item.name}{% endif %}
        `,
        class: "window"
    });
});

var config = {
```
and then in the module config itself, used the DATA from perimeterWindowSections (in this example) 
```js
{
    module: 'MMM-HomeAssistantDisplay',
    position: 'top_right',
    classes:"page2",
    config: {
        host: "192.168.2.33",
        token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiIzNDRkZDU4ZjVmMTk0ZDZiYjljOWY4YmNiZWIxNGM5YiIsImlhdCI6MTczMzg0MDQ0MywiZXhwIjoyMDQ5MjAwNDQzfQ.tKV1Dxya5T_V6SkHQSksKcf_KtT7XooUz4JLe2U94is",
        port: 8123,
        useTLS: false,
        title: "Open Windows",
        useModuleTigger: false,
        class: "windows",
        sections: [
            ...perimeterWindowSections,   <------ here, this means expand the variable here
        ]
    },
},
```

the code before var config =  runs when the file is loaded thru require
so the perimeterWindowSections variable is filled 

and then the ...perimeterWindowSections later unloads the array..
easy to change the number of elements in the list.. just add another to the list of variables at the top..

oops.. by the time MMM-Config sees this, the code at the top is not visible and the expansion has already been done
so MMM-Config gets the RIGHT config, BUT when saved, the list creation code at the top is gone and the use of the expansion is gone, replaced by the actual array entries..(in this case) 

saving the top code is easy using awk (in linux) 
```
awk '/config\s*=\s*{/{exit} 1' MagicMirror/config/config.js
```
and one could find the array expansion lines with 
```sh 
awk -F. '/\s*\.\.\.(.*[^,])/ {print $4}' ../MagicMirror/config/config.js
```

are there other operators?

**Comment by eouia** [comment]
Just Idea.
1. Create an empty `_config.js`.
2. Read and execute the original `config.js` in `MMM-Config` to get computed config values, then operate the works.
3. Then, save the result config into `_config.js`. The original `config.js` would leave as it was.
4. Add some script to load `_config.js` when MM is booted. (AFAIK, loading custom `config` other than original `config.js` might be possible.)

**Comment by eouia** [comment]
When you need to reload the current config, 
1) If there is no change in `config.js`, just load `_config.js`
2) If there is some change in `config.js`, first load `config.js` then parse it, then load `_config.js` and merge them.

**Comment by sdetweil** [comment]
thanks.. I load the existing config.js with require(). it executes all the code,
so and the code at the top is not exported, so it is invisible. 

the expansion has been done , so I don't see it being used.. 

I can search the text config.js and save/restore the top part, and detect the use of ... expansion and restore that on config save
the form for this module would make the array read only so it can't be modified in the form. 

I was just thinking if there are other js language syntax that could be used like expansion..  as I design this fix..

**Comment by sdetweil** [comment]
MMM-Config creates a new config.js adding/removing modules, changing all the config options
so the _config won't work in my design.. 

I can save the top as a file and re-include it.. and I can detect when/where ... expansion is used in the text config and put it back in the new config.js

**Comment by eouia** [comment]
Well, I cannot guess any easy solution to achieve your goal. 

> MMM-Config creates a new config.js adding/removing modules, changing all the config options
so the _config won't work in my design..

Did you read this? https://github.com/sdetweil/MMM-Config/issues/49#issuecomment-2536440573

**Comment by sdetweil** [comment]
yeh, read comment.. design is different make new file, save old file

**Comment by sdetweil** [comment]
branch with_prefix has a working solution for extra code and useage in config.js

**Comment by sdetweil** [comment]
released Dec 31, 2024
