### ISSUE TITLE
module works only if mm is installed in ~/MagicMirror

### ISSUE THREAD

**Issue by khassel** [sdetweil/MMM-Config#5]
First thanks @sdetweil for this module and the idea.

Tried to run it in my setup where mm is not installed in the home directory. This doesn't work because of

- fix `MagicMirror` in `base` [here](https://github.com/sdetweil/MMM-Config/blob/82f5e2080959c38bd566a0909a0276f5de837a37/test_convert.sh#L4)
- wrong `fp` [here](https://github.com/sdetweil/MMM-Config/blob/82f5e2080959c38bd566a0909a0276f5de837a37/scripts/buildschema3.js#L112)

After "fixing" this by setting the correct values directly in the source code the module config site is loaded.

**Comment by sdetweil** [comment]
can u give me an example of what the other path is...

**Comment by khassel** [comment]
in my docker setup the mm path is `opt/magic_mirror`.

**Comment by khassel** [comment]
here what is in the `fp` variable:

````
[21.05.2021 23:27.12.945] [LOG]   stdout: d=/opt/magic_mirror/modules/MMM-Config
completed

[21.05.2021 23:27.12.945] [ERROR] stderr 2: node:internal/fs/utils:343
    throw err;
    ^

Error: ENOENT: no such file or directory, scandir '/opt/magic_mirror/modules/MagicMirror/translations'
````

**Comment by sdetweil** [comment]
cool.. thanks.. just pushed fix

the fp was because I was debugging under webstorm, and it forces all lowercase folder names.. doah..
so I had to copy over to work there..

**Comment by khassel** [comment]
thank you, also working on my side.
