### ISSUE TITLE
two module defaults mixed up

### ISSUE THREAD

**Issue by lavolp3** [sdetweil/MMM-Config#7]
For a reason I don't know yet two module defaults have been mixed resulting in an error.
From defaults.js
```
MMM_Fantasy_Premier_League_defaults:  {
MMM_OpenWeatherForecast_defaults:  {
                password: '',
    apikey: "",
                username: '',
    latitude: "",
                updateInterval: 21600000, // Every 6 hours
    longitude: "",
                leagueIds: [
    updateInterval: 10, // minutes
                         {
    requestDelay: 0,
    language: config.language,
id: 313
    units: "metric",
                }
    displayKmhForWind: false,
, // Overall
    concise: true,
                         {
    iconset: "1c",
id: 226
    colored: true,
    useAnimatedIcons: true,
    animateMainIconOnly: true,
    animatedIconStartDelay: 1000,
    mainIconSize: 100,
    forecastIconSize: 70,
    updateFadeSpeed: 500,
    showFeelsLikeTemp: false,
    showSummary: true,

    showCurrentConditions: true,
    showExtraCurrentConditions: true,
    extraCurrentConditions:  {
      highLowTemp: true,
      precipitation: true,
      sunrise: true,
   ...
```

Above, the MMM-Fantasy-Premier-league defaults are indented by tabs while the openweather defaults are intended by spaces.
It might be important that MMM-Fantasy-Premier-League is NOT present in config.js

**Comment by sdetweil** [comment]
interesting.. I don't see that .. 
can you  go to the module folder and do 
./test_convert.sh override 
it will rescan all modules and produce a new defaults.js,  and schema3.json file if successful..
tabs/spaces are the module authors  source file, I just copy the lines. 
it shouldn't matter, when loaded the javascript engine parses out the white space

**Comment by sdetweil** [comment]
the defaults scanner processes each module in single file, no async overlap..

**Comment by lavolp3** [comment]
did a git pull and recreated defaults.js and it seems to be fixed now. Thanks!
